language: clojure
script:
  - lein2 test
  - lein2 with-profile +1.5 test
  - lein2 with-profile +1.6 test
  - lein2 with-profile +1.7 test
  - lein2 with-profile +lint cljfmt check
  - lein2 with-profile +lint eastwood
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
